console.log(1 + 1);
console.log(2 - 1);
console.log(3 * 4);
console.log(40 / 5);
console.log(10 % 3);
var b = 1;
console.log(++b);
console.log(b--);
console.log(b);
console.log(1 < 2);
console.log(1 > 2);
console.log(1 <= 2);
console.log(2 <= 2);
